repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.13 # Use the ref you want to point at
  hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-ruff